### ISSUE TITLE
Changing focal length?

### ISSUE THREAD

**Issue by antithing** [ChristopherRemde/Projection_shadow#1]
Hi, and thanks for making this available! I have it working great, as long as my camera is on 35mm focal length. Changing the focal does not update the size of the decal. 

Can you please point me in the right direction to add this functionality?

Thanks!

**Comment by ChristopherRemde** [comment]
Hey Anithing!

I haven't used UE4 or the script since a few years, so I'm kinda out of the game atm. I'll try to see if I can find some time to look into this issue, but at the moment I can't promise anithing ;)

But I think the script takes the FOV of the camera in account, so maybe try changing that?

**Comment by antithing** [comment]
Ah, you are correct, i was setting the FOV on the wrong component. Thanks!
